import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "@/components/Provider/ClientProvider";
import { GoogleOAuthProvider } from '@react-oauth/google';

export const metadata: Metadata = {
  title: "Auctregal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GoogleOAuthProvider clientId="876041787638-brlpgoujj1trkqnicssmn8eg0ol7f2hl.apps.googleusercontent.com">
          <ClientProvider>
            {children}
          </ClientProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
